
def sanitize(userInput):

    userInput = str(userInput)
    
    userInput = userInput.replace(" ", "")
    userInput = userInput.replace("-", "")
    userInput = userInput.replace("_", "")
    userInput = userInput.replace("'", "")
    userInput = userInput.replace('"', '')
    userInput = userInput.replace("=", "")
    userInput = userInput.replace("+", "")
    userInput = userInput.replace(".", "")
    userInput = userInput.replace(">", "")
    userInput = userInput.replace(",", "")
    userInput = userInput.replace("<", "")
    userInput = userInput.replace(";", "")
    userInput = userInput.replace(":", "")
    userInput = userInput.replace("[", "")
    userInput = userInput.replace("{", "")
    userInput = userInput.replace("]", "")
    userInput = userInput.replace("}", "")
    userInput = userInput.replace("`", "")
    userInput = userInput.replace("~", "")
    userInput = userInput.replace("!", "")
    userInput = userInput.replace("@", "")
    userInput = userInput.replace("#", "")
    userInput = userInput.replace("$", "")
    userInput = userInput.replace("%", "")
    userInput = userInput.replace("^", "")
    userInput = userInput.replace("&", "")
    userInput = userInput.replace("*", "")
    userInput = userInput.replace("(", "")
    userInput = userInput.replace(")", "")
    userInput = userInput.replace("a", "").replace("A", "")
    userInput = userInput.replace("b", "").replace("B", "")
    userInput = userInput.replace("c", "").replace("C", "")
    userInput = userInput.replace("d", "").replace("D", "")
    userInput = userInput.replace("e", "").replace("E", "")
    userInput = userInput.replace("f", "").replace("F", "")
    userInput = userInput.replace("g", "").replace("G", "")
    userInput = userInput.replace("h", "").replace("H", "")
    userInput = userInput.replace("i", "").replace("I", "")
    userInput = userInput.replace("j", "").replace("J", "")
    userInput = userInput.replace("k", "").replace("K", "")
    userInput = userInput.replace("l", "").replace("L", "")
    userInput = userInput.replace("m", "").replace("M", "")
    userInput = userInput.replace("n", "").replace("N", "")
    userInput = userInput.replace("o", "").replace("O", "")
    userInput = userInput.replace("p", "").replace("P", "")
    userInput = userInput.replace("q", "").replace("Q", "")
    userInput = userInput.replace("r", "").replace("R", "")
    userInput = userInput.replace("s", "").replace("S", "")
    userInput = userInput.replace("t", "").replace("T", "")
    userInput = userInput.replace("u", "").replace("U", "")
    userInput = userInput.replace("v", "").replace("V", "")
    userInput = userInput.replace("w", "").replace("W", "")
    userInput = userInput.replace("x", "").replace("X", "")
    userInput = userInput.replace("y", "").replace("Y", "")
    userInput = userInput.replace("z", "").replace("Z", "")
    userInput = userInput.replace("0", "")

    userInput = userInput[0]
    userInput = int(userInput)
    
    return userInput
